services:
  - type: web
    name: react-login-client
    env: static
    staticPublishPath: client/dist
    buildCommand: npm run build:client

  - type: web
    name: react-login-server
    env: node
    buildCommand: npm run build:server
    startCommand: cd server && npm start
